

export interface EmojiItem {
  emoji: string;
  name: string;
  keywords: string[];
  supportsSkinTone?: boolean;
  isCustom?: boolean;
  url?: string;
}

export interface EmojiCategory {
  id: string;
  name: string;
  emojis: EmojiItem[];
}

export const SKIN_TONES = {
  default: '',
  light: '🏻',
  mediumLight: '🏼',
  medium: '🏽',
  mediumDark: '🏾',
  dark: '🏿',
} as const;

export type SkinTone = keyof typeof SKIN_TONES;

export const SKIN_TONE_LABELS: Record<SkinTone, string> = {
  default: 'Default',
  light: 'Tone 1',
  mediumLight: 'Tone 2',
  medium: 'Tone 3',
  mediumDark: 'Tone 4',
  dark: 'Tone 5',
};

export function applySkinTone(emoji: string, skinTone: SkinTone): string {
  if (skinTone === 'default') return emoji;
  return emoji + SKIN_TONES[skinTone];
}

export function getSkinToneVariants(emoji: string): string[] {
  return [
    emoji,
    applySkinTone(emoji, 'light'),
    applySkinTone(emoji, 'mediumLight'),
    applySkinTone(emoji, 'medium'),
    applySkinTone(emoji, 'mediumDark'),
    applySkinTone(emoji, 'dark'),
  ];
}


export const DEFAULT_REACTION_EMOJIS = ['👍', '❤️', '😂', '😮', '😢', '😡', '🔥'];


export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'smileys',
    name: 'Smileys & Emotion',
    emojis: [
      { emoji: '😀', name: 'grinning', keywords: ['happy', 'smile', 'grin'] },
      { emoji: '😃', name: 'smiley', keywords: ['happy', 'smile'] },
      { emoji: '😄', name: 'smile', keywords: ['happy', 'joy'] },
      { emoji: '😁', name: 'grin', keywords: ['happy', 'smile'] },
      { emoji: '😆', name: 'laughing', keywords: ['happy', 'haha', 'lol'] },
      { emoji: '😅', name: 'sweat_smile', keywords: ['hot', 'happy'] },
      { emoji: '🤣', name: 'rofl', keywords: ['laughing', 'lol', 'haha'] },
      { emoji: '😂', name: 'joy', keywords: ['tears', 'laughing', 'lol'] },
      { emoji: '🙂', name: 'slightly_smiling', keywords: ['smile'] },
      { emoji: '🙃', name: 'upside_down', keywords: ['silly'] },
      { emoji: '😉', name: 'wink', keywords: ['flirt', 'smile'] },
      { emoji: '😊', name: 'blush', keywords: ['happy', 'smile'] },
      { emoji: '😇', name: 'innocent', keywords: ['angel', 'halo'] },
      { emoji: '🥰', name: 'smiling_hearts', keywords: ['love', 'crush'] },
      { emoji: '😍', name: 'heart_eyes', keywords: ['love', 'crush'] },
      { emoji: '🤩', name: 'star_struck', keywords: ['eyes', 'amazing'] },
      { emoji: '😘', name: 'kissing_heart', keywords: ['love', 'kiss'] },
      { emoji: '😗', name: 'kissing', keywords: ['kiss'] },
      { emoji: '😚', name: 'kissing_closed_eyes', keywords: ['kiss'] },
      { emoji: '😙', name: 'kissing_smiling_eyes', keywords: ['kiss'] },
      { emoji: '🥲', name: 'smiling_tear', keywords: ['sad', 'happy'] },
      { emoji: '😋', name: 'yum', keywords: ['tongue', 'taste'] },
      { emoji: '😛', name: 'stuck_out_tongue', keywords: ['tongue'] },
      { emoji: '😜', name: 'stuck_out_tongue_winking_eye', keywords: ['tongue', 'wink'] },
      { emoji: '🤪', name: 'zany', keywords: ['crazy', 'wild'] },
      { emoji: '😝', name: 'stuck_out_tongue_closed_eyes', keywords: ['tongue'] },
      { emoji: '🤑', name: 'money_mouth', keywords: ['money', 'rich'] },
      { emoji: '🤗', name: 'hugs', keywords: ['hug'] },
      { emoji: '🤭', name: 'hand_over_mouth', keywords: ['quiet', 'whoops'] },
      { emoji: '🤫', name: 'shushing', keywords: ['quiet', 'shh'] },
      { emoji: '🤔', name: 'thinking', keywords: ['hmm', 'think'] },
      { emoji: '🤐', name: 'zipper_mouth', keywords: ['quiet', 'sealed'] },
      { emoji: '🤨', name: 'raised_eyebrow', keywords: ['suspicious', 'skeptical'] },
      { emoji: '😐', name: 'neutral', keywords: ['meh'] },
      { emoji: '😑', name: 'expressionless', keywords: ['blank'] },
      { emoji: '😶', name: 'no_mouth', keywords: ['silence'] },
      { emoji: '😏', name: 'smirk', keywords: ['smug'] },
      { emoji: '😒', name: 'unamused', keywords: ['annoyed'] },
      { emoji: '🙄', name: 'eye_roll', keywords: ['annoyed'] },
      { emoji: '😬', name: 'grimacing', keywords: ['awkward'] },
      { emoji: '🤥', name: 'lying', keywords: ['pinocchio', 'lie'] },
      { emoji: '😌', name: 'relieved', keywords: ['calm', 'peaceful'] },
      { emoji: '😔', name: 'pensive', keywords: ['sad', 'down'] },
      { emoji: '😪', name: 'sleepy', keywords: ['tired', 'sleep'] },
      { emoji: '🤤', name: 'drooling', keywords: ['hungry'] },
      { emoji: '😴', name: 'sleeping', keywords: ['sleep', 'zzz'] },
      { emoji: '😷', name: 'mask', keywords: ['sick', 'doctor'] },
      { emoji: '🤒', name: 'thermometer', keywords: ['sick', 'ill'] },
      { emoji: '🤕', name: 'head_bandage', keywords: ['hurt', 'injured'] },
      { emoji: '🤢', name: 'nauseated', keywords: ['sick', 'gross'] },
      { emoji: '🤮', name: 'vomiting', keywords: ['sick', 'gross'] },
      { emoji: '🤧', name: 'sneezing', keywords: ['sick', 'sneeze'] },
      { emoji: '🥵', name: 'hot', keywords: ['heat', 'sweat'] },
      { emoji: '🥶', name: 'cold', keywords: ['freezing', 'frozen'] },
      { emoji: '😵', name: 'dizzy', keywords: ['confused', 'spiral'] },
      { emoji: '🤯', name: 'exploding_head', keywords: ['mind_blown', 'shocked'] },
      { emoji: '🤠', name: 'cowboy', keywords: ['hat', 'western'] },
      { emoji: '🥳', name: 'partying', keywords: ['celebration', 'party'] },
      { emoji: '🥸', name: 'disguised', keywords: ['glasses', 'incognito'] },
      { emoji: '😎', name: 'sunglasses', keywords: ['cool'] },
      { emoji: '🤓', name: 'nerd', keywords: ['geek', 'glasses'] },
      { emoji: '🧐', name: 'monocle', keywords: ['curious'] },
      { emoji: '😕', name: 'confused', keywords: ['puzzled'] },
      { emoji: '😟', name: 'worried', keywords: ['concern'] },
      { emoji: '🙁', name: 'slightly_frowning', keywords: ['sad'] },
      { emoji: '☹️', name: 'frowning', keywords: ['sad'] },
      { emoji: '😮', name: 'open_mouth', keywords: ['surprise', 'wow'] },
      { emoji: '😯', name: 'hushed', keywords: ['surprise', 'shock'] },
      { emoji: '😲', name: 'astonished', keywords: ['amazed', 'gasp'] },
      { emoji: '😳', name: 'flushed', keywords: ['embarrassed'] },
      { emoji: '🥺', name: 'pleading', keywords: ['puppy_eyes', 'sad'] },
      { emoji: '😦', name: 'frowning_open_mouth', keywords: ['sad', 'surprise'] },
      { emoji: '😧', name: 'anguished', keywords: ['sad', 'pain'] },
      { emoji: '😨', name: 'fearful', keywords: ['scared', 'shocked'] },
      { emoji: '😰', name: 'cold_sweat', keywords: ['nervous'] },
      { emoji: '😥', name: 'disappointed_relieved', keywords: ['sad', 'relief'] },
      { emoji: '😢', name: 'cry', keywords: ['sad', 'tear'] },
      { emoji: '😭', name: 'sob', keywords: ['cry', 'sad', 'tears'] },
      { emoji: '😱', name: 'scream', keywords: ['fear', 'horror'] },
      { emoji: '😖', name: 'confounded', keywords: ['confused', 'sick'] },
      { emoji: '😣', name: 'persevere', keywords: ['struggling'] },
      { emoji: '😞', name: 'disappointed', keywords: ['sad'] },
      { emoji: '😓', name: 'sweat', keywords: ['hard_work'] },
      { emoji: '😩', name: 'weary', keywords: ['tired'] },
      { emoji: '😫', name: 'tired', keywords: ['exhausted'] },
      { emoji: '🥱', name: 'yawning', keywords: ['tired', 'bored'] },
      { emoji: '😤', name: 'triumph', keywords: ['proud', 'steaming'] },
      { emoji: '😡', name: 'rage', keywords: ['angry', 'mad'] },
      { emoji: '😠', name: 'angry', keywords: ['mad', 'annoyed'] },
      { emoji: '🤬', name: 'cursing', keywords: ['swearing', 'censored'] },
      { emoji: '😈', name: 'smiling_imp', keywords: ['devil', 'evil'] },
      { emoji: '👿', name: 'imp', keywords: ['devil', 'angry'] },
      { emoji: '💀', name: 'skull', keywords: ['dead', 'death'] },
      { emoji: '☠️', name: 'skull_crossbones', keywords: ['danger', 'pirate'] },
      { emoji: '💩', name: 'poop', keywords: ['shit'] },
      { emoji: '🤡', name: 'clown', keywords: ['joker'] },
      { emoji: '👹', name: 'ogre', keywords: ['monster'] },
      { emoji: '👺', name: 'goblin', keywords: ['monster'] },
      { emoji: '👻', name: 'ghost', keywords: ['halloween'] },
      { emoji: '👽', name: 'alien', keywords: ['ufo', 'space'] },
      { emoji: '👾', name: 'space_invader', keywords: ['game', 'retro'] },
      { emoji: '🤖', name: 'robot', keywords: ['bot'] },
      { emoji: '💋', name: 'kiss', keywords: ['lips', 'love'] },
      { emoji: '💘', name: 'cupid', keywords: ['love', 'heart'] },
      { emoji: '💝', name: 'gift_heart', keywords: ['love', 'chocolate'] },
      { emoji: '💖', name: 'sparkling_heart', keywords: ['love'] },
      { emoji: '💗', name: 'heartpulse', keywords: ['love'] },
      { emoji: '💓', name: 'heartbeat', keywords: ['love'] },
      { emoji: '💞', name: 'revolving_hearts', keywords: ['love'] },
      { emoji: '💕', name: 'two_hearts', keywords: ['love'] },
      { emoji: '💟', name: 'heart_decoration', keywords: ['love'] },
      { emoji: '❣️', name: 'heart_exclamation', keywords: ['love'] },
      { emoji: '💔', name: 'broken_heart', keywords: ['sad', 'heartbreak'] },
      { emoji: '❤️', name: 'heart', keywords: ['love'] },
      { emoji: '🧡', name: 'orange_heart', keywords: ['love'] },
      { emoji: '💛', name: 'yellow_heart', keywords: ['love'] },
      { emoji: '💚', name: 'green_heart', keywords: ['love'] },
      { emoji: '💙', name: 'blue_heart', keywords: ['love'] },
      { emoji: '💜', name: 'purple_heart', keywords: ['love'] },
      { emoji: '🤎', name: 'brown_heart', keywords: ['love'] },
      { emoji: '🖤', name: 'black_heart', keywords: ['evil', 'wicked'] },
      { emoji: '🤍', name: 'white_heart', keywords: ['love', 'pure'] },
    ],
  },
  {
    id: 'gestures',
    name: 'People & Body',
    emojis: [
      { emoji: '👍', name: 'thumbs_up', keywords: ['like', 'yes', 'approve'], supportsSkinTone: true },
      { emoji: '👎', name: 'thumbs_down', keywords: ['dislike', 'no', 'disapprove'], supportsSkinTone: true },
      { emoji: '👊', name: 'fist', keywords: ['punch', 'power'], supportsSkinTone: true },
      { emoji: '✊', name: 'raised_fist', keywords: ['solidarity', 'power'], supportsSkinTone: true },
      { emoji: '🤛', name: 'left_fist', keywords: ['fist_bump'], supportsSkinTone: true },
      { emoji: '🤜', name: 'right_fist', keywords: ['fist_bump'], supportsSkinTone: true },
      { emoji: '👏', name: 'clap', keywords: ['applause', 'congrats'], supportsSkinTone: true },
      { emoji: '🙌', name: 'raised_hands', keywords: ['celebrate', 'hooray'], supportsSkinTone: true },
      { emoji: '👐', name: 'open_hands', keywords: ['hug'], supportsSkinTone: true },
      { emoji: '🤲', name: 'palms_up', keywords: ['please', 'pray'], supportsSkinTone: true },
      { emoji: '🤝', name: 'handshake', keywords: ['deal', 'agreement'], supportsSkinTone: true },
      { emoji: '🙏', name: 'pray', keywords: ['please', 'thanks', 'namaste'], supportsSkinTone: true },
      { emoji: '✌️', name: 'victory', keywords: ['peace'], supportsSkinTone: true },
      { emoji: '🤞', name: 'crossed_fingers', keywords: ['luck', 'hope'], supportsSkinTone: true },
      { emoji: '🤟', name: 'love_you', keywords: ['ily'], supportsSkinTone: true },
      { emoji: '🤘', name: 'metal', keywords: ['rock'], supportsSkinTone: true },
      { emoji: '🤙', name: 'call_me', keywords: ['phone', 'hang_loose'], supportsSkinTone: true },
      { emoji: '👈', name: 'point_left', keywords: ['direction'], supportsSkinTone: true },
      { emoji: '👉', name: 'point_right', keywords: ['direction'], supportsSkinTone: true },
      { emoji: '👆', name: 'point_up', keywords: ['direction'], supportsSkinTone: true },
      { emoji: '👇', name: 'point_down', keywords: ['direction'], supportsSkinTone: true },
      { emoji: '☝️', name: 'index_pointing_up', keywords: ['one', 'direction'], supportsSkinTone: true },
      { emoji: '✋', name: 'raised_hand', keywords: ['stop', 'high_five'], supportsSkinTone: true },
      { emoji: '🤚', name: 'raised_back_hand', keywords: ['stop'], supportsSkinTone: true },
      { emoji: '🖐️', name: 'hand_splayed', keywords: ['five', 'stop'], supportsSkinTone: true },
      { emoji: '🖖', name: 'vulcan', keywords: ['spock', 'star_trek'], supportsSkinTone: true },
      { emoji: '👋', name: 'wave', keywords: ['hello', 'goodbye', 'hi'], supportsSkinTone: true },
      { emoji: '🤙', name: 'call_me', keywords: ['phone'], supportsSkinTone: true },
      { emoji: '💪', name: 'muscle', keywords: ['strong', 'flex', 'bicep'], supportsSkinTone: true },
      { emoji: '🦵', name: 'leg', keywords: ['kick'], supportsSkinTone: true },
      { emoji: '🦶', name: 'foot', keywords: ['kick'], supportsSkinTone: true },
      { emoji: '👂', name: 'ear', keywords: ['hear', 'listen'], supportsSkinTone: true },
      { emoji: '🦻', name: 'ear_hearing_aid', keywords: ['accessibility'], supportsSkinTone: true },
      { emoji: '👃', name: 'nose', keywords: ['smell'], supportsSkinTone: true },
      { emoji: '🧠', name: 'brain', keywords: ['smart', 'intelligent'] },
      { emoji: '🦷', name: 'tooth', keywords: ['dentist'] },
      { emoji: '🦴', name: 'bone', keywords: ['skeleton'] },
      { emoji: '👀', name: 'eyes', keywords: ['look', 'watch'] },
      { emoji: '👁️', name: 'eye', keywords: ['look'] },
      { emoji: '👅', name: 'tongue', keywords: ['taste'] },
      { emoji: '👄', name: 'lips', keywords: ['kiss', 'mouth'] },
    ],
  },
  {
    id: 'nature',
    name: 'Animals & Nature',
    emojis: [
      { emoji: '🐶', name: 'dog', keywords: ['puppy', 'pet'] },
      { emoji: '🐱', name: 'cat', keywords: ['kitty', 'pet'] },
      { emoji: '🐭', name: 'mouse', keywords: ['rat'] },
      { emoji: '🐹', name: 'hamster', keywords: ['pet'] },
      { emoji: '🐰', name: 'rabbit', keywords: ['bunny'] },
      { emoji: '🦊', name: 'fox', keywords: ['clever'] },
      { emoji: '🐻', name: 'bear', keywords: ['animal'] },
      { emoji: '🐼', name: 'panda', keywords: ['animal'] },
      { emoji: '🐨', name: 'koala', keywords: ['animal'] },
      { emoji: '🐯', name: 'tiger', keywords: ['animal'] },
      { emoji: '🦁', name: 'lion', keywords: ['animal', 'king'] },
      { emoji: '🐮', name: 'cow', keywords: ['animal'] },
      { emoji: '🐷', name: 'pig', keywords: ['animal'] },
      { emoji: '🐸', name: 'frog', keywords: ['animal'] },
      { emoji: '🐵', name: 'monkey', keywords: ['animal'] },
      { emoji: '🐔', name: 'chicken', keywords: ['bird'] },
      { emoji: '🐧', name: 'penguin', keywords: ['bird'] },
      { emoji: '🐦', name: 'bird', keywords: ['animal'] },
      { emoji: '🐤', name: 'baby_chick', keywords: ['bird'] },
      { emoji: '🦆', name: 'duck', keywords: ['bird'] },
      { emoji: '🦅', name: 'eagle', keywords: ['bird'] },
      { emoji: '🦉', name: 'owl', keywords: ['bird', 'wise'] },
      { emoji: '🦇', name: 'bat', keywords: ['vampire'] },
      { emoji: '🐺', name: 'wolf', keywords: ['animal'] },
      { emoji: '🐗', name: 'boar', keywords: ['animal'] },
      { emoji: '🐴', name: 'horse', keywords: ['animal'] },
      { emoji: '🦄', name: 'unicorn', keywords: ['magical'] },
      { emoji: '🐝', name: 'bee', keywords: ['insect'] },
      { emoji: '🐛', name: 'bug', keywords: ['insect'] },
      { emoji: '🦋', name: 'butterfly', keywords: ['insect'] },
      { emoji: '🐌', name: 'snail', keywords: ['slow'] },
      { emoji: '🐞', name: 'ladybug', keywords: ['insect'] },
      { emoji: '🐜', name: 'ant', keywords: ['insect'] },
      { emoji: '🦗', name: 'cricket', keywords: ['insect'] },
      { emoji: '🕷️', name: 'spider', keywords: ['insect'] },
      { emoji: '🦂', name: 'scorpion', keywords: ['insect'] },
      { emoji: '🐢', name: 'turtle', keywords: ['slow'] },
      { emoji: '🐍', name: 'snake', keywords: ['reptile'] },
      { emoji: '🦎', name: 'lizard', keywords: ['reptile'] },
      { emoji: '🦖', name: 't-rex', keywords: ['dinosaur'] },
      { emoji: '🦕', name: 'sauropod', keywords: ['dinosaur'] },
      { emoji: '🐙', name: 'octopus', keywords: ['sea'] },
      { emoji: '🦑', name: 'squid', keywords: ['sea'] },
      { emoji: '🦐', name: 'shrimp', keywords: ['seafood'] },
      { emoji: '🦞', name: 'lobster', keywords: ['seafood'] },
      { emoji: '🦀', name: 'crab', keywords: ['seafood'] },
      { emoji: '🐡', name: 'blowfish', keywords: ['fish'] },
      { emoji: '🐠', name: 'tropical_fish', keywords: ['fish'] },
      { emoji: '🐟', name: 'fish', keywords: ['animal'] },
      { emoji: '🐬', name: 'dolphin', keywords: ['sea'] },
      { emoji: '🐳', name: 'whale', keywords: ['sea'] },
      { emoji: '🐋', name: 'whale2', keywords: ['sea'] },
      { emoji: '🦈', name: 'shark', keywords: ['sea', 'dangerous'] },
      { emoji: '🌸', name: 'cherry_blossom', keywords: ['flower', 'spring'] },
      { emoji: '💮', name: 'white_flower', keywords: ['flower'] },
      { emoji: '🏵️', name: 'rosette', keywords: ['flower'] },
      { emoji: '🌹', name: 'rose', keywords: ['flower', 'love'] },
      { emoji: '🥀', name: 'wilted_rose', keywords: ['flower', 'sad'] },
      { emoji: '🌺', name: 'hibiscus', keywords: ['flower'] },
      { emoji: '🌻', name: 'sunflower', keywords: ['flower'] },
      { emoji: '🌼', name: 'blossom', keywords: ['flower'] },
      { emoji: '🌷', name: 'tulip', keywords: ['flower'] },
      { emoji: '🌱', name: 'seedling', keywords: ['plant', 'growing'] },
      { emoji: '🌲', name: 'evergreen_tree', keywords: ['tree', 'nature'] },
      { emoji: '🌳', name: 'deciduous_tree', keywords: ['tree', 'nature'] },
      { emoji: '🌴', name: 'palm_tree', keywords: ['tree', 'tropical'] },
      { emoji: '🌵', name: 'cactus', keywords: ['plant', 'desert'] },
      { emoji: '🌾', name: 'ear_of_rice', keywords: ['plant'] },
      { emoji: '🌿', name: 'herb', keywords: ['plant', 'leaf'] },
      { emoji: '☘️', name: 'shamrock', keywords: ['luck', 'irish'] },
      { emoji: '🍀', name: 'four_leaf_clover', keywords: ['luck'] },
      { emoji: '🍁', name: 'maple_leaf', keywords: ['leaf', 'canada', 'fall'] },
      { emoji: '🍂', name: 'fallen_leaf', keywords: ['leaf', 'autumn'] },
      { emoji: '🍃', name: 'leaves', keywords: ['leaf', 'nature'] },
    ],
  },
  {
    id: 'food',
    name: 'Food & Drink',
    emojis: [
      { emoji: '🍇', name: 'grapes', keywords: ['fruit'] },
      { emoji: '🍈', name: 'melon', keywords: ['fruit'] },
      { emoji: '🍉', name: 'watermelon', keywords: ['fruit'] },
      { emoji: '🍊', name: 'tangerine', keywords: ['fruit', 'orange'] },
      { emoji: '🍋', name: 'lemon', keywords: ['fruit'] },
      { emoji: '🍌', name: 'banana', keywords: ['fruit'] },
      { emoji: '🍍', name: 'pineapple', keywords: ['fruit'] },
      { emoji: '🥭', name: 'mango', keywords: ['fruit'] },
      { emoji: '🍎', name: 'apple', keywords: ['fruit'] },
      { emoji: '🍏', name: 'green_apple', keywords: ['fruit'] },
      { emoji: '🍐', name: 'pear', keywords: ['fruit'] },
      { emoji: '🍑', name: 'peach', keywords: ['fruit'] },
      { emoji: '🍒', name: 'cherries', keywords: ['fruit'] },
      { emoji: '🍓', name: 'strawberry', keywords: ['fruit'] },
      { emoji: '🥝', name: 'kiwi', keywords: ['fruit'] },
      { emoji: '🍅', name: 'tomato', keywords: ['vegetable'] },
      { emoji: '🥥', name: 'coconut', keywords: ['fruit'] },
      { emoji: '🥑', name: 'avocado', keywords: ['fruit'] },
      { emoji: '🍆', name: 'eggplant', keywords: ['vegetable'] },
      { emoji: '🥔', name: 'potato', keywords: ['vegetable'] },
      { emoji: '🥕', name: 'carrot', keywords: ['vegetable'] },
      { emoji: '🌽', name: 'corn', keywords: ['vegetable'] },
      { emoji: '🌶️', name: 'hot_pepper', keywords: ['spicy'] },
      { emoji: '🥒', name: 'cucumber', keywords: ['vegetable'] },
      { emoji: '🥬', name: 'leafy_green', keywords: ['vegetable'] },
      { emoji: '🥦', name: 'broccoli', keywords: ['vegetable'] },
      { emoji: '🧄', name: 'garlic', keywords: ['vegetable'] },
      { emoji: '🧅', name: 'onion', keywords: ['vegetable'] },
      { emoji: '🍄', name: 'mushroom', keywords: ['vegetable'] },
      { emoji: '🥜', name: 'peanuts', keywords: ['nut'] },
      { emoji: '🌰', name: 'chestnut', keywords: ['nut'] },
      { emoji: '🍞', name: 'bread', keywords: ['food'] },
      { emoji: '🥐', name: 'croissant', keywords: ['bread', 'french'] },
      { emoji: '🥖', name: 'baguette', keywords: ['bread', 'french'] },
      { emoji: '🥨', name: 'pretzel', keywords: ['bread'] },
      { emoji: '🥯', name: 'bagel', keywords: ['bread'] },
      { emoji: '🥞', name: 'pancakes', keywords: ['breakfast'] },
      { emoji: '🧇', name: 'waffle', keywords: ['breakfast'] },
      { emoji: '🧀', name: 'cheese', keywords: ['food'] },
      { emoji: '🍖', name: 'meat_on_bone', keywords: ['food'] },
      { emoji: '🍗', name: 'poultry_leg', keywords: ['food', 'chicken'] },
      { emoji: '🥩', name: 'steak', keywords: ['meat', 'food'] },
      { emoji: '🥓', name: 'bacon', keywords: ['food'] },
      { emoji: '🍔', name: 'hamburger', keywords: ['food', 'burger'] },
      { emoji: '🍟', name: 'fries', keywords: ['food'] },
      { emoji: '🍕', name: 'pizza', keywords: ['food'] },
      { emoji: '🌭', name: 'hotdog', keywords: ['food'] },
      { emoji: '🥪', name: 'sandwich', keywords: ['food'] },
      { emoji: '🌮', name: 'taco', keywords: ['food', 'mexican'] },
      { emoji: '🌯', name: 'burrito', keywords: ['food', 'mexican'] },
      { emoji: '🥙', name: 'stuffed_flatbread', keywords: ['food'] },
      { emoji: '🧆', name: 'falafel', keywords: ['food'] },
      { emoji: '🥚', name: 'egg', keywords: ['food'] },
      { emoji: '🍳', name: 'cooking', keywords: ['food', 'egg', 'breakfast'] },
      { emoji: '🥘', name: 'paella', keywords: ['food'] },
      { emoji: '🍲', name: 'stew', keywords: ['food'] },
      { emoji: '🥣', name: 'bowl_with_spoon', keywords: ['food', 'cereal'] },
      { emoji: '🥗', name: 'salad', keywords: ['food', 'healthy'] },
      { emoji: '🍿', name: 'popcorn', keywords: ['snack', 'movie'] },
      { emoji: '🧈', name: 'butter', keywords: ['food'] },
      { emoji: '🧂', name: 'salt', keywords: ['food'] },
      { emoji: '🥫', name: 'canned_food', keywords: ['food'] },
      { emoji: '🍱', name: 'bento', keywords: ['food', 'japanese'] },
      { emoji: '🍘', name: 'rice_cracker', keywords: ['food'] },
      { emoji: '🍙', name: 'rice_ball', keywords: ['food', 'japanese'] },
      { emoji: '🍚', name: 'rice', keywords: ['food'] },
      { emoji: '🍛', name: 'curry', keywords: ['food'] },
      { emoji: '🍜', name: 'ramen', keywords: ['food', 'noodles'] },
      { emoji: '🍝', name: 'spaghetti', keywords: ['food', 'pasta'] },
      { emoji: '🍠', name: 'sweet_potato', keywords: ['food'] },
      { emoji: '🍢', name: 'oden', keywords: ['food'] },
      { emoji: '🍣', name: 'sushi', keywords: ['food', 'japanese'] },
      { emoji: '🍤', name: 'fried_shrimp', keywords: ['food'] },
      { emoji: '🍥', name: 'fish_cake', keywords: ['food'] },
      { emoji: '🥮', name: 'moon_cake', keywords: ['food'] },
      { emoji: '🍡', name: 'dango', keywords: ['food', 'japanese'] },
      { emoji: '🥟', name: 'dumpling', keywords: ['food'] },
      { emoji: '🥠', name: 'fortune_cookie', keywords: ['food'] },
      { emoji: '🥡', name: 'takeout_box', keywords: ['food', 'chinese'] },
      { emoji: '🦀', name: 'crab', keywords: ['food', 'seafood'] },
      { emoji: '🦞', name: 'lobster', keywords: ['food', 'seafood'] },
      { emoji: '🦐', name: 'shrimp', keywords: ['food', 'seafood'] },
      { emoji: '🦑', name: 'squid', keywords: ['food', 'seafood'] },
      { emoji: '🦪', name: 'oyster', keywords: ['food', 'seafood'] },
      { emoji: '🍦', name: 'icecream', keywords: ['dessert', 'sweet'] },
      { emoji: '🍧', name: 'shaved_ice', keywords: ['dessert', 'sweet'] },
      { emoji: '🍨', name: 'ice_cream', keywords: ['dessert', 'sweet'] },
      { emoji: '🍩', name: 'doughnut', keywords: ['dessert', 'sweet'] },
      { emoji: '🍪', name: 'cookie', keywords: ['dessert', 'sweet'] },
      { emoji: '🎂', name: 'birthday', keywords: ['cake', 'party'] },
      { emoji: '🍰', name: 'cake', keywords: ['dessert', 'sweet'] },
      { emoji: '🧁', name: 'cupcake', keywords: ['dessert', 'sweet'] },
      { emoji: '🥧', name: 'pie', keywords: ['dessert', 'sweet'] },
      { emoji: '🍫', name: 'chocolate_bar', keywords: ['dessert', 'sweet'] },
      { emoji: '🍬', name: 'candy', keywords: ['dessert', 'sweet'] },
      { emoji: '🍭', name: 'lollipop', keywords: ['dessert', 'sweet'] },
      { emoji: '🍮', name: 'custard', keywords: ['dessert', 'sweet'] },
      { emoji: '🍯', name: 'honey_pot', keywords: ['sweet'] },
      { emoji: '🍼', name: 'baby_bottle', keywords: ['milk', 'drink'] },
      { emoji: '🥛', name: 'milk', keywords: ['drink'] },
      { emoji: '☕', name: 'coffee', keywords: ['drink', 'hot'] },
      { emoji: '🍵', name: 'tea', keywords: ['drink', 'hot'] },
      { emoji: '🧃', name: 'beverage_box', keywords: ['drink', 'juice'] },
      { emoji: '🥤', name: 'cup_with_straw', keywords: ['drink'] },
      { emoji: '🍶', name: 'sake', keywords: ['drink', 'alcohol'] },
      { emoji: '🍺', name: 'beer', keywords: ['drink', 'alcohol'] },
      { emoji: '🍻', name: 'beers', keywords: ['drink', 'cheers', 'alcohol'] },
      { emoji: '🥂', name: 'champagne_glass', keywords: ['drink', 'cheers', 'alcohol'] },
      { emoji: '🍷', name: 'wine_glass', keywords: ['drink', 'alcohol'] },
      { emoji: '🥃', name: 'tumbler_glass', keywords: ['drink', 'whiskey', 'alcohol'] },
      { emoji: '🍸', name: 'cocktail', keywords: ['drink', 'alcohol'] },
      { emoji: '🍹', name: 'tropical_drink', keywords: ['drink', 'alcohol'] },
      { emoji: '🧉', name: 'mate', keywords: ['drink'] },
      { emoji: '🧊', name: 'ice_cube', keywords: ['cold'] },
      { emoji: '🥄', name: 'spoon', keywords: ['utensil'] },
      { emoji: '🍴', name: 'fork_and_knife', keywords: ['utensil'] },
      { emoji: '🍽️', name: 'plate_with_cutlery', keywords: ['food'] },
    ],
  },
  {
    id: 'activities',
    name: 'Activities',
    emojis: [
      { emoji: '⚽', name: 'soccer', keywords: ['sports', 'football'] },
      { emoji: '🏀', name: 'basketball', keywords: ['sports', 'NBA'] },
      { emoji: '🏈', name: 'football', keywords: ['sports', 'NFL'] },
      { emoji: '⚾', name: 'baseball', keywords: ['sports'] },
      { emoji: '🥎', name: 'softball', keywords: ['sports'] },
      { emoji: '🎾', name: 'tennis', keywords: ['sports'] },
      { emoji: '🏐', name: 'volleyball', keywords: ['sports'] },
      { emoji: '🏉', name: 'rugby', keywords: ['sports'] },
      { emoji: '🥏', name: 'frisbee', keywords: ['sports'] },
      { emoji: '🎱', name: '8ball', keywords: ['pool', 'billiards'] },
      { emoji: '🪀', name: 'yo-yo', keywords: ['toy'] },
      { emoji: '🏓', name: 'ping_pong', keywords: ['sports'] },
      { emoji: '🏸', name: 'badminton', keywords: ['sports'] },
      { emoji: '🏒', name: 'hockey', keywords: ['sports'] },
      { emoji: '🏑', name: 'field_hockey', keywords: ['sports'] },
      { emoji: '🥍', name: 'lacrosse', keywords: ['sports'] },
      { emoji: '🏏', name: 'cricket', keywords: ['sports'] },
      { emoji: '🥅', name: 'goal', keywords: ['sports'] },
      { emoji: '⛳', name: 'golf', keywords: ['sports'] },
      { emoji: '🪁', name: 'kite', keywords: ['fly'] },
      { emoji: '🏹', name: 'bow_and_arrow', keywords: ['archery'] },
      { emoji: '🎣', name: 'fishing_pole', keywords: ['fish'] },
      { emoji: '🤿', name: 'diving_mask', keywords: ['scuba'] },
      { emoji: '🥊', name: 'boxing_glove', keywords: ['sports'] },
      { emoji: '🥋', name: 'martial_arts_uniform', keywords: ['karate'] },
      { emoji: '🎽', name: 'running_shirt', keywords: ['sports'] },
      { emoji: '🛹', name: 'skateboard', keywords: ['sports'] },
      { emoji: '🛼', name: 'roller_skate', keywords: ['sports'] },
      { emoji: '🛷', name: 'sled', keywords: ['winter'] },
      { emoji: '⛸️', name: 'ice_skate', keywords: ['winter'] },
      { emoji: '🥌', name: 'curling_stone', keywords: ['sports'] },
      { emoji: '🎿', name: 'ski', keywords: ['sports', 'winter'] },
      { emoji: '⛷️', name: 'skier', keywords: ['sports', 'winter'] },
      { emoji: '🏂', name: 'snowboarder', keywords: ['sports', 'winter'] },
      { emoji: '🪂', name: 'parachute', keywords: ['skydiving'] },
      { emoji: '🏋️', name: 'weightlifter', keywords: ['gym', 'workout'] },
      { emoji: '🤼', name: 'wrestlers', keywords: ['sports'] },
      { emoji: '🤸', name: 'cartwheeling', keywords: ['gymnastics'] },
      { emoji: '⛹️', name: 'basketball_player', keywords: ['sports'] },
      { emoji: '🤺', name: 'fencer', keywords: ['sports'] },
      { emoji: '🤾', name: 'handball', keywords: ['sports'] },
      { emoji: '🏌️', name: 'golfer', keywords: ['sports'] },
      { emoji: '🏇', name: 'horse_racing', keywords: ['sports'] },
      { emoji: '🧘', name: 'lotus_position', keywords: ['yoga', 'meditation'] },
      { emoji: '🏄', name: 'surfer', keywords: ['sports'] },
      { emoji: '🏊', name: 'swimmer', keywords: ['sports'] },
      { emoji: '🤽', name: 'water_polo', keywords: ['sports'] },
      { emoji: '🚣', name: 'rowboat', keywords: ['sports'] },
      { emoji: '🧗', name: 'climber', keywords: ['sports'] },
      { emoji: '🚴', name: 'bicyclist', keywords: ['sports'] },
      { emoji: '🚵', name: 'mountain_bicyclist', keywords: ['sports'] },
      { emoji: '🤹', name: 'juggling', keywords: ['circus'] },
      { emoji: '🎪', name: 'circus_tent', keywords: ['entertainment'] },
      { emoji: '🎭', name: 'performing_arts', keywords: ['theater'] },
      { emoji: '🩰', name: 'ballet_shoes', keywords: ['dance'] },
      { emoji: '🎨', name: 'art', keywords: ['painting', 'creative'] },
      { emoji: '🎬', name: 'clapper', keywords: ['movie', 'film'] },
      { emoji: '🎤', name: 'microphone', keywords: ['sing', 'music'] },
      { emoji: '🎧', name: 'headphones', keywords: ['music'] },
      { emoji: '🎼', name: 'musical_score', keywords: ['music'] },
      { emoji: '🎹', name: 'musical_keyboard', keywords: ['piano', 'music'] },
      { emoji: '🥁', name: 'drum', keywords: ['music'] },
      { emoji: '🎷', name: 'saxophone', keywords: ['music'] },
      { emoji: '🎺', name: 'trumpet', keywords: ['music'] },
      { emoji: '🎸', name: 'guitar', keywords: ['music', 'rock'] },
      { emoji: '🪕', name: 'banjo', keywords: ['music'] },
      { emoji: '🎻', name: 'violin', keywords: ['music'] },
      { emoji: '🎲', name: 'dice', keywords: ['game', 'gambling'] },
      { emoji: '♟️', name: 'chess_pawn', keywords: ['game'] },
      { emoji: '🎯', name: 'dart', keywords: ['game', 'target'] },
      { emoji: '🎳', name: 'bowling', keywords: ['game'] },
      { emoji: '🎮', name: 'video_game', keywords: ['gaming', 'controller'] },
      { emoji: '🎰', name: 'slot_machine', keywords: ['gambling'] },
      { emoji: '🧩', name: 'jigsaw', keywords: ['puzzle'] },
      { emoji: '🏆', name: 'trophy', keywords: ['win', 'award'] },
      { emoji: '🥇', name: 'first_place', keywords: ['gold', 'winner'] },
      { emoji: '🥈', name: 'second_place', keywords: ['silver'] },
      { emoji: '🥉', name: 'third_place', keywords: ['bronze'] },
      { emoji: '🏅', name: 'medal', keywords: ['award'] },
      { emoji: '🎖️', name: 'military_medal', keywords: ['award'] },
      { emoji: '🏵️', name: 'rosette', keywords: ['award'] },
      { emoji: '🎗️', name: 'reminder_ribbon', keywords: ['awareness'] },
      { emoji: '🎫', name: 'ticket', keywords: ['event'] },
      { emoji: '🎟️', name: 'admission_tickets', keywords: ['event'] },
    ],
  },
  {
    id: 'travel',
    name: 'Travel & Places',
    emojis: [
      { emoji: '🚗', name: 'car', keywords: ['vehicle', 'transportation'] },
      { emoji: '🚕', name: 'taxi', keywords: ['vehicle', 'transportation'] },
      { emoji: '🚙', name: 'blue_car', keywords: ['vehicle', 'transportation'] },
      { emoji: '🚌', name: 'bus', keywords: ['vehicle', 'transportation'] },
      { emoji: '🚎', name: 'trolleybus', keywords: ['vehicle', 'transportation'] },
      { emoji: '🏎️', name: 'racing_car', keywords: ['fast', 'vehicle'] },
      { emoji: '🚓', name: 'police_car', keywords: ['vehicle', 'emergency'] },
      { emoji: '🚑', name: 'ambulance', keywords: ['vehicle', 'emergency'] },
      { emoji: '🚒', name: 'fire_engine', keywords: ['vehicle', 'emergency'] },
      { emoji: '🚐', name: 'minibus', keywords: ['vehicle', 'transportation'] },
      { emoji: '🛻', name: 'pickup_truck', keywords: ['vehicle'] },
      { emoji: '🚚', name: 'truck', keywords: ['vehicle'] },
      { emoji: '🚛', name: 'articulated_lorry', keywords: ['vehicle'] },
      { emoji: '🚜', name: 'tractor', keywords: ['vehicle', 'farm'] },
      { emoji: '🏍️', name: 'motorcycle', keywords: ['vehicle'] },
      { emoji: '🛵', name: 'scooter', keywords: ['vehicle'] },
      { emoji: '🦽', name: 'manual_wheelchair', keywords: ['accessibility'] },
      { emoji: '🦼', name: 'motorized_wheelchair', keywords: ['accessibility'] },
      { emoji: '🛺', name: 'auto_rickshaw', keywords: ['vehicle'] },
      { emoji: '🚲', name: 'bike', keywords: ['bicycle', 'vehicle'] },
      { emoji: '🛴', name: 'scooter', keywords: ['vehicle'] },
      { emoji: '🚏', name: 'bus_stop', keywords: ['transportation'] },
      { emoji: '🛣️', name: 'motorway', keywords: ['road'] },
      { emoji: '🛤️', name: 'railway_track', keywords: ['train'] },
      { emoji: '⛽', name: 'gas_station', keywords: ['fuel'] },
      { emoji: '🚨', name: 'rotating_light', keywords: ['emergency', 'police'] },
      { emoji: '🚥', name: 'traffic_light', keywords: ['transportation'] },
      { emoji: '🚦', name: 'vertical_traffic_light', keywords: ['transportation'] },
      { emoji: '🛑', name: 'stop_sign', keywords: ['traffic'] },
      { emoji: '🚧', name: 'construction', keywords: ['warning'] },
      { emoji: '⚓', name: 'anchor', keywords: ['ship', 'boat'] },
      { emoji: '⛵', name: 'sailboat', keywords: ['boat', 'ship'] },
      { emoji: '🛶', name: 'canoe', keywords: ['boat'] },
      { emoji: '🚤', name: 'speedboat', keywords: ['boat', 'ship'] },
      { emoji: '🛳️', name: 'passenger_ship', keywords: ['cruise'] },
      { emoji: '⛴️', name: 'ferry', keywords: ['boat'] },
      { emoji: '🛥️', name: 'motor_boat', keywords: ['boat'] },
      { emoji: '🚢', name: 'ship', keywords: ['boat'] },
      { emoji: '✈️', name: 'airplane', keywords: ['flight', 'travel'] },
      { emoji: '🛩️', name: 'small_airplane', keywords: ['flight', 'travel'] },
      { emoji: '🛫', name: 'airplane_departure', keywords: ['flight', 'travel'] },
      { emoji: '🛬', name: 'airplane_arriving', keywords: ['flight', 'travel'] },
      { emoji: '🪂', name: 'parachute', keywords: ['skydiving'] },
      { emoji: '💺', name: 'seat', keywords: ['airplane'] },
      { emoji: '🚁', name: 'helicopter', keywords: ['vehicle'] },
      { emoji: '🚟', name: 'suspension_railway', keywords: ['transportation'] },
      { emoji: '🚠', name: 'mountain_cableway', keywords: ['transportation'] },
      { emoji: '🚡', name: 'aerial_tramway', keywords: ['transportation'] },
      { emoji: '🛰️', name: 'satellite', keywords: ['space'] },
      { emoji: '🚀', name: 'rocket', keywords: ['space', 'fast'] },
      { emoji: '🛸', name: 'flying_saucer', keywords: ['ufo', 'alien'] },
      { emoji: '🌍', name: 'earth_africa', keywords: ['world', 'planet'] },
      { emoji: '🌎', name: 'earth_americas', keywords: ['world', 'planet'] },
      { emoji: '🌏', name: 'earth_asia', keywords: ['world', 'planet'] },
      { emoji: '🌐', name: 'globe_with_meridians', keywords: ['world', 'internet'] },
      { emoji: '🗺️', name: 'world_map', keywords: ['travel'] },
      { emoji: '🗾', name: 'japan', keywords: ['map'] },
      { emoji: '🧭', name: 'compass', keywords: ['navigation'] },
      { emoji: '🏔️', name: 'snow_capped_mountain', keywords: ['nature'] },
      { emoji: '⛰️', name: 'mountain', keywords: ['nature'] },
      { emoji: '🌋', name: 'volcano', keywords: ['nature'] },
      { emoji: '🗻', name: 'mount_fuji', keywords: ['mountain'] },
      { emoji: '🏕️', name: 'camping', keywords: ['outdoors'] },
      { emoji: '🏖️', name: 'beach', keywords: ['vacation', 'summer'] },
      { emoji: '🏝️', name: 'desert_island', keywords: ['vacation'] },
      { emoji: '🏜️', name: 'desert', keywords: ['nature'] },
      { emoji: '🏞️', name: 'national_park', keywords: ['nature'] },
      { emoji: '🏟️', name: 'stadium', keywords: ['sports'] },
      { emoji: '🏛️', name: 'classical_building', keywords: ['architecture'] },
      { emoji: '🏗️', name: 'building_construction', keywords: ['construction'] },
      { emoji: '🧱', name: 'bricks', keywords: ['building'] },
      { emoji: '🏘️', name: 'houses', keywords: ['buildings'] },
      { emoji: '🏚️', name: 'derelict_house', keywords: ['abandoned'] },
      { emoji: '🏠', name: 'house', keywords: ['home', 'building'] },
      { emoji: '🏡', name: 'house_with_garden', keywords: ['home', 'building'] },
      { emoji: '🏢', name: 'office', keywords: ['building', 'work'] },
      { emoji: '🏣', name: 'post_office', keywords: ['building'] },
      { emoji: '🏤', name: 'european_post_office', keywords: ['building'] },
      { emoji: '🏥', name: 'hospital', keywords: ['building', 'health'] },
      { emoji: '🏦', name: 'bank', keywords: ['building', 'money'] },
      { emoji: '🏨', name: 'hotel', keywords: ['building', 'travel'] },
      { emoji: '🏩', name: 'love_hotel', keywords: ['building'] },
      { emoji: '🏪', name: 'convenience_store', keywords: ['building', 'shop'] },
      { emoji: '🏫', name: 'school', keywords: ['building', 'education'] },
      { emoji: '🏬', name: 'department_store', keywords: ['building', 'shop'] },
      { emoji: '🏭', name: 'factory', keywords: ['building', 'industrial'] },
      { emoji: '🏯', name: 'japanese_castle', keywords: ['building'] },
      { emoji: '🏰', name: 'european_castle', keywords: ['building'] },
      { emoji: '💒', name: 'wedding', keywords: ['marriage', 'church'] },
      { emoji: '🗼', name: 'tokyo_tower', keywords: ['building'] },
      { emoji: '🗽', name: 'statue_of_liberty', keywords: ['usa'] },
    ],
  },
  {
    id: 'objects',
    name: 'Objects',
    emojis: [
      { emoji: '⌚', name: 'watch', keywords: ['time'] },
      { emoji: '📱', name: 'iphone', keywords: ['phone', 'mobile'] },
      { emoji: '📲', name: 'calling', keywords: ['phone', 'call'] },
      { emoji: '💻', name: 'computer', keywords: ['laptop', 'pc'] },
      { emoji: '⌨️', name: 'keyboard', keywords: ['computer'] },
      { emoji: '🖥️', name: 'desktop', keywords: ['computer'] },
      { emoji: '🖨️', name: 'printer', keywords: ['computer'] },
      { emoji: '🖱️', name: 'mouse', keywords: ['computer'] },
      { emoji: '🖲️', name: 'trackball', keywords: ['computer'] },
      { emoji: '🕹️', name: 'joystick', keywords: ['game'] },
      { emoji: '🗜️', name: 'compression', keywords: ['tool'] },
      { emoji: '💾', name: 'floppy_disk', keywords: ['save', 'computer'] },
      { emoji: '💿', name: 'cd', keywords: ['disk'] },
      { emoji: '📀', name: 'dvd', keywords: ['disk'] },
      { emoji: '📼', name: 'vhs', keywords: ['video'] },
      { emoji: '📷', name: 'camera', keywords: ['photo'] },
      { emoji: '📸', name: 'camera_flash', keywords: ['photo'] },
      { emoji: '📹', name: 'video_camera', keywords: ['film'] },
      { emoji: '🎥', name: 'movie_camera', keywords: ['film'] },
      { emoji: '📽️', name: 'film_projector', keywords: ['video'] },
      { emoji: '🎞️', name: 'film_frames', keywords: ['movie'] },
      { emoji: '📞', name: 'telephone_receiver', keywords: ['phone'] },
      { emoji: '☎️', name: 'phone', keywords: ['telephone'] },
      { emoji: '📟', name: 'pager', keywords: ['communication'] },
      { emoji: '📠', name: 'fax', keywords: ['communication'] },
      { emoji: '📺', name: 'tv', keywords: ['television'] },
      { emoji: '📻', name: 'radio', keywords: ['music'] },
      { emoji: '🎙️', name: 'studio_microphone', keywords: ['podcast'] },
      { emoji: '🎚️', name: 'level_slider', keywords: ['music'] },
      { emoji: '🎛️', name: 'control_knobs', keywords: ['music'] },
      { emoji: '🧭', name: 'compass', keywords: ['navigation'] },
      { emoji: '⏱️', name: 'stopwatch', keywords: ['time'] },
      { emoji: '⏲️', name: 'timer', keywords: ['time'] },
      { emoji: '⏰', name: 'alarm_clock', keywords: ['time', 'wake'] },
      { emoji: '🕰️', name: 'clock', keywords: ['time'] },
      { emoji: '⌛', name: 'hourglass', keywords: ['time'] },
      { emoji: '⏳', name: 'hourglass_flowing_sand', keywords: ['time'] },
      { emoji: '📡', name: 'satellite_antenna', keywords: ['communication'] },
      { emoji: '🔋', name: 'battery', keywords: ['power'] },
      { emoji: '🔌', name: 'electric_plug', keywords: ['power'] },
      { emoji: '💡', name: 'bulb', keywords: ['light', 'idea'] },
      { emoji: '🔦', name: 'flashlight', keywords: ['light'] },
      { emoji: '🕯️', name: 'candle', keywords: ['light'] },
      { emoji: '🪔', name: 'diya_lamp', keywords: ['light'] },
      { emoji: '🧯', name: 'fire_extinguisher', keywords: ['safety'] },
      { emoji: '🛢️', name: 'oil_drum', keywords: ['barrel'] },
      { emoji: '💸', name: 'money_with_wings', keywords: ['dollar', 'cash'] },
      { emoji: '💵', name: 'dollar', keywords: ['money', 'cash'] },
      { emoji: '💴', name: 'yen', keywords: ['money', 'japanese'] },
      { emoji: '💶', name: 'euro', keywords: ['money'] },
      { emoji: '💷', name: 'pound', keywords: ['money', 'british'] },
      { emoji: '💰', name: 'moneybag', keywords: ['money', 'rich'] },
      { emoji: '💳', name: 'credit_card', keywords: ['money', 'payment'] },
      { emoji: '💎', name: 'gem', keywords: ['diamond', 'jewel'] },
      { emoji: '⚖️', name: 'scales', keywords: ['balance', 'justice'] },
      { emoji: '🧰', name: 'toolbox', keywords: ['tools'] },
      { emoji: '🔧', name: 'wrench', keywords: ['tool'] },
      { emoji: '🔨', name: 'hammer', keywords: ['tool'] },
      { emoji: '⚒️', name: 'hammer_pick', keywords: ['tool'] },
      { emoji: '🛠️', name: 'tools', keywords: ['hammer', 'wrench'] },
      { emoji: '⛏️', name: 'pick', keywords: ['tool', 'mining'] },
      { emoji: '🔩', name: 'nut_and_bolt', keywords: ['tool'] },
      { emoji: '⚙️', name: 'gear', keywords: ['settings'] },
      { emoji: '🧱', name: 'brick', keywords: ['building'] },
      { emoji: '⛓️', name: 'chains', keywords: ['lock'] },
      { emoji: '🧲', name: 'magnet', keywords: ['attraction'] },
      { emoji: '🔫', name: 'gun', keywords: ['weapon', 'pistol'] },
      { emoji: '💣', name: 'bomb', keywords: ['explosion'] },
      { emoji: '🧨', name: 'firecracker', keywords: ['explosion'] },
      { emoji: '🔪', name: 'knife', keywords: ['weapon', 'cut'] },
      { emoji: '🗡️', name: 'dagger', keywords: ['weapon'] },
      { emoji: '⚔️', name: 'crossed_swords', keywords: ['weapon'] },
      { emoji: '🛡️', name: 'shield', keywords: ['protection'] },
      { emoji: '🚬', name: 'smoking', keywords: ['cigarette'] },
      { emoji: '⚰️', name: 'coffin', keywords: ['death'] },
      { emoji: '⚱️', name: 'urn', keywords: ['death'] },
      { emoji: '🏺', name: 'amphora', keywords: ['vase'] },
      { emoji: '🔮', name: 'crystal_ball', keywords: ['fortune', 'magic'] },
      { emoji: '📿', name: 'prayer_beads', keywords: ['religion'] },
      { emoji: '🧿', name: 'nazar_amulet', keywords: ['evil_eye'] },
      { emoji: '💈', name: 'barber', keywords: ['haircut'] },
      { emoji: '⚗️', name: 'alembic', keywords: ['chemistry'] },
      { emoji: '🔭', name: 'telescope', keywords: ['space', 'stars'] },
      { emoji: '🔬', name: 'microscope', keywords: ['science'] },
      { emoji: '🕳️', name: 'hole', keywords: ['empty'] },
      { emoji: '🩹', name: 'adhesive_bandage', keywords: ['heal'] },
      { emoji: '🩺', name: 'stethoscope', keywords: ['doctor', 'health'] },
      { emoji: '💊', name: 'pill', keywords: ['medicine', 'health'] },
      { emoji: '💉', name: 'syringe', keywords: ['health', 'medicine', 'needle'] },
      { emoji: '🩸', name: 'drop_of_blood', keywords: ['health'] },
      { emoji: '🧬', name: 'dna', keywords: ['science', 'genetics'] },
      { emoji: '🦠', name: 'microbe', keywords: ['germ', 'virus'] },
      { emoji: '🧫', name: 'petri_dish', keywords: ['science', 'bacteria'] },
      { emoji: '🧪', name: 'test_tube', keywords: ['science', 'chemistry'] },
      { emoji: '🌡️', name: 'thermometer', keywords: ['temperature', 'sick'] },
      { emoji: '🧹', name: 'broom', keywords: ['clean', 'sweep'] },
      { emoji: '🧺', name: 'basket', keywords: ['laundry'] },
      { emoji: '🧻', name: 'roll_of_paper', keywords: ['toilet_paper'] },
      { emoji: '🚽', name: 'toilet', keywords: ['bathroom'] },
      { emoji: '🚰', name: 'potable_water', keywords: ['drink'] },
      { emoji: '🚿', name: 'shower', keywords: ['bath'] },
      { emoji: '🛁', name: 'bathtub', keywords: ['bath'] },
      { emoji: '🛀', name: 'bath', keywords: ['shower', 'relax'] },
      { emoji: '🧼', name: 'soap', keywords: ['clean'] },
      { emoji: '🧽', name: 'sponge', keywords: ['clean'] },
      { emoji: '🧴', name: 'lotion_bottle', keywords: ['moisturizer'] },
      { emoji: '🛎️', name: 'bellhop', keywords: ['hotel', 'service'] },
      { emoji: '🔑', name: 'key', keywords: ['lock', 'password'] },
      { emoji: '🗝️', name: 'old_key', keywords: ['lock'] },
      { emoji: '🚪', name: 'door', keywords: ['entry'] },
      { emoji: '🪑', name: 'chair', keywords: ['sit', 'furniture'] },
      { emoji: '🛋️', name: 'couch', keywords: ['sofa', 'furniture'] },
      { emoji: '🛏️', name: 'bed', keywords: ['sleep', 'furniture'] },
      { emoji: '🧸', name: 'teddy_bear', keywords: ['toy'] },
      { emoji: '🖼️', name: 'frame_picture', keywords: ['art'] },
      { emoji: '🛍️', name: 'shopping_bags', keywords: ['shopping'] },
      { emoji: '🛒', name: 'shopping_cart', keywords: ['shopping'] },
      { emoji: '🎁', name: 'gift', keywords: ['present', 'birthday'] },
      { emoji: '🎈', name: 'balloon', keywords: ['party', 'celebration'] },
      { emoji: '🎏', name: 'flags', keywords: ['celebration'] },
      { emoji: '🎀', name: 'ribbon', keywords: ['decoration'] },
      { emoji: '🎊', name: 'confetti_ball', keywords: ['party'] },
      { emoji: '🎉', name: 'tada', keywords: ['party', 'celebration', 'congrats'] },
      { emoji: '🎎', name: 'dolls', keywords: ['japanese'] },
      { emoji: '🏮', name: 'izakaya_lantern', keywords: ['light', 'japanese'] },
      { emoji: '🎐', name: 'wind_chime', keywords: ['japanese'] },
      { emoji: '🧧', name: 'red_envelope', keywords: ['gift', 'money'] },
      { emoji: '✉️', name: 'envelope', keywords: ['email', 'letter'] },
      { emoji: '📩', name: 'envelope_with_arrow', keywords: ['email'] },
      { emoji: '📨', name: 'incoming_envelope', keywords: ['email'] },
      { emoji: '📧', name: 'email', keywords: ['letter'] },
      { emoji: '💌', name: 'love_letter', keywords: ['email', 'envelope'] },
      { emoji: '📥', name: 'inbox_tray', keywords: ['email'] },
      { emoji: '📤', name: 'outbox_tray', keywords: ['email'] },
      { emoji: '📦', name: 'package', keywords: ['shipping', 'box'] },
      { emoji: '🏷️', name: 'label', keywords: ['tag'] },
      { emoji: '📪', name: 'mailbox_closed', keywords: ['email'] },
      { emoji: '📫', name: 'mailbox', keywords: ['email'] },
      { emoji: '📬', name: 'mailbox_with_mail', keywords: ['email'] },
      { emoji: '📭', name: 'mailbox_with_no_mail', keywords: ['email'] },
      { emoji: '📮', name: 'postbox', keywords: ['email'] },
      { emoji: '📯', name: 'postal_horn', keywords: ['communication'] },
      { emoji: '📜', name: 'scroll', keywords: ['paper', 'document'] },
      { emoji: '📃', name: 'page_with_curl', keywords: ['document'] },
      { emoji: '📄', name: 'page_facing_up', keywords: ['document'] },
      { emoji: '📑', name: 'bookmark_tabs', keywords: ['document'] },
      { emoji: '🧾', name: 'receipt', keywords: ['bill'] },
      { emoji: '📊', name: 'bar_chart', keywords: ['graph', 'stats'] },
      { emoji: '📈', name: 'chart_increasing', keywords: ['graph', 'success'] },
      { emoji: '📉', name: 'chart_decreasing', keywords: ['graph', 'down'] },
      { emoji: '🗒️', name: 'notepad', keywords: ['notes'] },
      { emoji: '🗓️', name: 'calendar_spiral', keywords: ['date'] },
      { emoji: '📆', name: 'calendar', keywords: ['schedule', 'date'] },
      { emoji: '📅', name: 'date', keywords: ['calendar', 'schedule'] },
      { emoji: '📇', name: 'card_index', keywords: ['contacts'] },
      { emoji: '🗃️', name: 'card_box', keywords: ['storage'] },
      { emoji: '🗳️', name: 'ballot_box', keywords: ['vote'] },
      { emoji: '🗄️', name: 'file_cabinet', keywords: ['storage'] },
      { emoji: '📋', name: 'clipboard', keywords: ['document'] },
      { emoji: '📁', name: 'file_folder', keywords: ['directory'] },
      { emoji: '📂', name: 'open_file_folder', keywords: ['directory'] },
      { emoji: '🗂️', name: 'dividers', keywords: ['organization'] },
      { emoji: '🗞️', name: 'newspaper_roll', keywords: ['news'] },
      { emoji: '📰', name: 'newspaper', keywords: ['news'] },
      { emoji: '📓', name: 'notebook', keywords: ['notes'] },
      { emoji: '📔', name: 'notebook_decorative_cover', keywords: ['notes'] },
      { emoji: '📒', name: 'ledger', keywords: ['notes'] },
      { emoji: '📕', name: 'closed_book', keywords: ['read', 'library'] },
      { emoji: '📗', name: 'green_book', keywords: ['read', 'library'] },
      { emoji: '📘', name: 'blue_book', keywords: ['read', 'library'] },
      { emoji: '📙', name: 'orange_book', keywords: ['read', 'library'] },
      { emoji: '📚', name: 'books', keywords: ['library', 'read'] },
      { emoji: '📖', name: 'book', keywords: ['read'] },
      { emoji: '🔖', name: 'bookmark', keywords: ['read'] },
      { emoji: '🧷', name: 'safety_pin', keywords: ['diaper'] },
      { emoji: '🔗', name: 'link', keywords: ['url'] },
      { emoji: '📎', name: 'paperclip', keywords: ['attachment'] },
      { emoji: '🖇️', name: 'paperclips', keywords: ['attachment'] },
      { emoji: '📐', name: 'triangular_ruler', keywords: ['math', 'architect'] },
      { emoji: '📏', name: 'straight_ruler', keywords: ['math'] },
      { emoji: '🧮', name: 'abacus', keywords: ['math'] },
      { emoji: '📌', name: 'pushpin', keywords: ['pin'] },
      { emoji: '📍', name: 'round_pushpin', keywords: ['location', 'pin'] },
      { emoji: '✂️', name: 'scissors', keywords: ['cut'] },
      { emoji: '🖊️', name: 'pen_ballpoint', keywords: ['write'] },
      { emoji: '🖋️', name: 'pen_fountain', keywords: ['write'] },
      { emoji: '✒️', name: 'black_nib', keywords: ['write'] },
      { emoji: '🖌️', name: 'paintbrush', keywords: ['art'] },
      { emoji: '🖍️', name: 'crayon', keywords: ['art'] },
      { emoji: '📝', name: 'pencil', keywords: ['write', 'note'] },
      { emoji: '✏️', name: 'pencil2', keywords: ['write'] },
      { emoji: '🔍', name: 'mag', keywords: ['search', 'zoom'] },
      { emoji: '🔎', name: 'mag_right', keywords: ['search', 'zoom'] },
      { emoji: '🔏', name: 'lock_with_ink_pen', keywords: ['security'] },
      { emoji: '🔐', name: 'closed_lock_with_key', keywords: ['security'] },
      { emoji: '🔒', name: 'lock', keywords: ['security', 'private'] },
      { emoji: '🔓', name: 'unlock', keywords: ['security'] },
    ],
  },
  {
    id: 'symbols',
    name: 'Symbols',
    emojis: [
      { emoji: '❤️', name: 'heart', keywords: ['love'] },
      { emoji: '🧡', name: 'orange_heart', keywords: ['love'] },
      { emoji: '💛', name: 'yellow_heart', keywords: ['love'] },
      { emoji: '💚', name: 'green_heart', keywords: ['love'] },
      { emoji: '💙', name: 'blue_heart', keywords: ['love'] },
      { emoji: '💜', name: 'purple_heart', keywords: ['love'] },
      { emoji: '🖤', name: 'black_heart', keywords: ['evil'] },
      { emoji: '🤍', name: 'white_heart', keywords: ['pure'] },
      { emoji: '🤎', name: 'brown_heart', keywords: ['love'] },
      { emoji: '💔', name: 'broken_heart', keywords: ['sad'] },
      { emoji: '❣️', name: 'heart_exclamation', keywords: ['love'] },
      { emoji: '💕', name: 'two_hearts', keywords: ['love'] },
      { emoji: '💞', name: 'revolving_hearts', keywords: ['love'] },
      { emoji: '💓', name: 'heartbeat', keywords: ['love'] },
      { emoji: '💗', name: 'heartpulse', keywords: ['love'] },
      { emoji: '💖', name: 'sparkling_heart', keywords: ['love'] },
      { emoji: '💘', name: 'cupid', keywords: ['love', 'arrow'] },
      { emoji: '💝', name: 'gift_heart', keywords: ['love', 'valentines'] },
      { emoji: '💟', name: 'heart_decoration', keywords: ['love'] },
      { emoji: '☮️', name: 'peace', keywords: ['hippie'] },
      { emoji: '✝️', name: 'cross', keywords: ['christianity'] },
      { emoji: '☪️', name: 'star_and_crescent', keywords: ['islam'] },
      { emoji: '🕉️', name: 'om_symbol', keywords: ['hinduism'] },
      { emoji: '☸️', name: 'wheel_of_dharma', keywords: ['buddhism'] },
      { emoji: '✡️', name: 'star_of_david', keywords: ['judaism'] },
      { emoji: '🔯', name: 'six_pointed_star', keywords: ['purple_square'] },
      { emoji: '🕎', name: 'menorah', keywords: ['candelabrum', 'jewish'] },
      { emoji: '☯️', name: 'yin_yang', keywords: ['balance'] },
      { emoji: '☦️', name: 'orthodox_cross', keywords: ['christianity'] },
      { emoji: '🛐', name: 'place_of_worship', keywords: ['religion'] },
      { emoji: '⛎', name: 'ophiuchus', keywords: ['zodiac'] },
      { emoji: '♈', name: 'aries', keywords: ['zodiac'] },
      { emoji: '♉', name: 'taurus', keywords: ['zodiac'] },
      { emoji: '♊', name: 'gemini', keywords: ['zodiac'] },
      { emoji: '♋', name: 'cancer', keywords: ['zodiac'] },
      { emoji: '♌', name: 'leo', keywords: ['zodiac'] },
      { emoji: '♍', name: 'virgo', keywords: ['zodiac'] },
      { emoji: '♎', name: 'libra', keywords: ['zodiac'] },
      { emoji: '♏', name: 'scorpius', keywords: ['zodiac'] },
      { emoji: '♐', name: 'sagittarius', keywords: ['zodiac'] },
      { emoji: '♑', name: 'capricorn', keywords: ['zodiac'] },
      { emoji: '♒', name: 'aquarius', keywords: ['zodiac'] },
      { emoji: '♓', name: 'pisces', keywords: ['zodiac'] },
      { emoji: '🆔', name: 'id', keywords: ['purple_square'] },
      { emoji: '⚛️', name: 'atom', keywords: ['science', 'physics'] },
      { emoji: '🉑', name: 'accept', keywords: ['ok', 'yes'] },
      { emoji: '☢️', name: 'radioactive', keywords: ['danger'] },
      { emoji: '☣️', name: 'biohazard', keywords: ['danger'] },
      { emoji: '📴', name: 'mobile_phone_off', keywords: ['phone', 'mute'] },
      { emoji: '📳', name: 'vibration_mode', keywords: ['phone'] },
      { emoji: '🈶', name: 'u6709', keywords: ['japanese'] },
      { emoji: '🈚', name: 'u7121', keywords: ['japanese', 'none'] },
      { emoji: '🈸', name: 'u7533', keywords: ['japanese', 'application'] },
      { emoji: '🈺', name: 'u55b6', keywords: ['japanese', 'open'] },
      { emoji: '🈷️', name: 'u6708', keywords: ['japanese', 'moon'] },
      { emoji: '✴️', name: 'eight_pointed_star', keywords: ['star'] },
      { emoji: '🆚', name: 'vs', keywords: ['vs', 'versus'] },
      { emoji: '💮', name: 'white_flower', keywords: ['japanese'] },
      { emoji: '🉐', name: 'ideograph_advantage', keywords: ['japanese'] },
      { emoji: '㊙️', name: 'secret', keywords: ['japanese', 'privacy'] },
      { emoji: '㊗️', name: 'congratulations', keywords: ['japanese'] },
      { emoji: '🈴', name: 'u5408', keywords: ['japanese', 'together'] },
      { emoji: '🈵', name: 'u6e80', keywords: ['japanese', 'full'] },
      { emoji: '🈹', name: 'u5272', keywords: ['japanese', 'discount'] },
      { emoji: '🈲', name: 'u7981', keywords: ['japanese', 'prohibited'] },
      { emoji: '🅰️', name: 'a', keywords: ['red_square', 'letter'] },
      { emoji: '🅱️', name: 'b', keywords: ['red_square', 'letter'] },
      { emoji: '🆎', name: 'ab', keywords: ['red_square', 'letters'] },
      { emoji: '🆑', name: 'cl', keywords: ['alphabet', 'words'] },
      { emoji: '🅾️', name: 'o2', keywords: ['alphabet', 'red_circle'] },
      { emoji: '🆘', name: 'sos', keywords: ['help', 'emergency'] },
      { emoji: '❌', name: 'x', keywords: ['no', 'delete', 'remove'] },
      { emoji: '⭕', name: 'o', keywords: ['circle'] },
      { emoji: '🛑', name: 'stop_sign', keywords: ['stop'] },
      { emoji: '⛔', name: 'no_entry', keywords: ['limit', 'stop'] },
      { emoji: '📛', name: 'name_badge', keywords: ['fire', 'forbid'] },
      { emoji: '🚫', name: 'no_entry_sign', keywords: ['block', 'forbidden'] },
      { emoji: '💯', name: '100', keywords: ['score', 'perfect'] },
      { emoji: '💢', name: 'anger', keywords: ['angry', 'mad'] },
      { emoji: '♨️', name: 'hotsprings', keywords: ['steam'] },
      { emoji: '🚷', name: 'no_pedestrians', keywords: ['rules', 'crossing'] },
      { emoji: '🚯', name: 'do_not_litter', keywords: ['trash'] },
      { emoji: '🚳', name: 'no_bicycles', keywords: ['bicycle', 'rules'] },
      { emoji: '🚱', name: 'non-potable_water', keywords: ['drink'] },
      { emoji: '🔞', name: 'underage', keywords: ['18', 'adult'] },
      { emoji: '📵', name: 'no_mobile_phones', keywords: ['phone', 'rules'] },
      { emoji: '🚭', name: 'no_smoking', keywords: ['cigarette', 'rules'] },
      { emoji: '❗', name: 'exclamation', keywords: ['bang', 'surprise'] },
      { emoji: '❕', name: 'grey_exclamation', keywords: ['surprise'] },
      { emoji: '❓', name: 'question', keywords: ['confused'] },
      { emoji: '❔', name: 'grey_question', keywords: ['confused'] },
      { emoji: '‼️', name: 'bangbang', keywords: ['exclamation'] },
      { emoji: '⁉️', name: 'interrobang', keywords: ['wat', 'punctuation'] },
      { emoji: '🔅', name: 'low_brightness', keywords: ['sun', 'dim'] },
      { emoji: '🔆', name: 'high_brightness', keywords: ['sun', 'light'] },
      { emoji: '〽️', name: 'part_alternation_mark', keywords: ['graph'] },
      { emoji: '⚠️', name: 'warning', keywords: ['danger', 'wip'] },
      { emoji: '🚸', name: 'children_crossing', keywords: ['school', 'warning'] },
      { emoji: '🔱', name: 'trident', keywords: ['spear', 'weapon'] },
      { emoji: '⚜️', name: 'fleur-de-lis', keywords: ['decorative', 'scout'] },
      { emoji: '🔰', name: 'beginner', keywords: ['badge', 'shield'] },
      { emoji: '♻️', name: 'recycle', keywords: ['environment', 'green'] },
      { emoji: '✅', name: 'white_check_mark', keywords: ['green_square', 'ok', 'yes'] },
      { emoji: '🈯', name: 'u6307', keywords: ['japanese', 'point'] },
      { emoji: '💹', name: 'chart', keywords: ['graph', 'presentation', 'stats'] },
      { emoji: '❇️', name: 'sparkle', keywords: ['green_square'] },
      { emoji: '✳️', name: 'eight_spoked_asterisk', keywords: ['star', 'sparkle'] },
      { emoji: '❎', name: 'negative_squared_cross_mark', keywords: ['x', 'green_square', 'no'] },
      { emoji: '🌐', name: 'globe_with_meridians', keywords: ['world', 'global', 'international'] },
      { emoji: '💠', name: 'diamond_shape_with_a_dot_inside', keywords: ['jewel', 'blue'] },
      { emoji: 'Ⓜ️', name: 'm', keywords: ['alphabet', 'blue_circle'] },
      { emoji: '🌀', name: 'cyclone', keywords: ['weather', 'swirl'] },
      { emoji: '💤', name: 'zzz', keywords: ['sleeping'] },
      { emoji: '🏧', name: 'atm', keywords: ['money', 'bank'] },
      { emoji: '🚾', name: 'wc', keywords: ['toilet', 'restroom'] },
      { emoji: '♿', name: 'wheelchair', keywords: ['accessibility'] },
      { emoji: '🅿️', name: 'parking', keywords: ['cars', 'blue_square'] },
      { emoji: '🈳', name: 'u7a7a', keywords: ['japanese', 'empty'] },
      { emoji: '🈂️', name: 'sa', keywords: ['japanese'] },
      { emoji: '🛂', name: 'passport_control', keywords: ['custom', 'blue_square'] },
      { emoji: '🛃', name: 'customs', keywords: ['passport', 'blue_square'] },
      { emoji: '🛄', name: 'baggage_claim', keywords: ['airport', 'blue_square'] },
      { emoji: '🛅', name: 'left_luggage', keywords: ['blue_square', 'travel'] },
      { emoji: '🚹', name: 'mens', keywords: ['toilet', 'restroom', 'wc', 'blue_square'] },
      { emoji: '🚺', name: 'womens', keywords: ['purple_square', 'woman', 'female', 'toilet'] },
      { emoji: '🚼', name: 'baby_symbol', keywords: ['orange_square', 'child'] },
      { emoji: '🚻', name: 'restroom', keywords: ['blue_square', 'toilet', 'refresh', 'wc'] },
      { emoji: '🚮', name: 'put_litter_in_its_place', keywords: ['blue_square', 'human', 'info'] },
      { emoji: '🎦', name: 'cinema', keywords: ['blue_square', 'record', 'film', 'movie'] },
      { emoji: '📶', name: 'signal_strength', keywords: ['blue_square', 'reception', 'phone', 'bars'] },
      { emoji: '🈁', name: 'koko', keywords: ['blue_square', 'japanese'] },
      { emoji: '🔣', name: 'symbols', keywords: ['blue_square', 'music', 'note', 'ampersand'] },
      { emoji: 'ℹ️', name: 'information_source', keywords: ['blue_square', 'alphabet', 'letter'] },
      { emoji: '🔤', name: 'abc', keywords: ['blue_square', 'alphabet'] },
      { emoji: '🔡', name: 'abcd', keywords: ['blue_square', 'alphabet'] },
      { emoji: '🔠', name: 'capital_abcd', keywords: ['alphabet', 'words', 'blue_square'] },
      { emoji: '🆖', name: 'ng', keywords: ['blue_square', 'words', 'shape'] },
      { emoji: '🆗', name: 'ok', keywords: ['good', 'agree', 'yes', 'blue_square'] },
      { emoji: '🆙', name: 'up', keywords: ['blue_square', 'above', 'high'] },
      { emoji: '🆒', name: 'cool', keywords: ['words', 'blue_square'] },
      { emoji: '🆕', name: 'new', keywords: ['blue_square', 'words', 'start'] },
      { emoji: '🆓', name: 'free', keywords: ['blue_square', 'words'] },
      { emoji: '0️⃣', name: 'zero', keywords: ['0', 'numbers', 'blue_square', 'null'] },
      { emoji: '1️⃣', name: 'one', keywords: ['blue_square', 'numbers', '1'] },
      { emoji: '2️⃣', name: 'two', keywords: ['numbers', '2', 'prime', 'blue_square'] },
      { emoji: '3️⃣', name: 'three', keywords: ['3', 'numbers', 'prime', 'blue_square'] },
      { emoji: '4️⃣', name: 'four', keywords: ['4', 'numbers', 'blue_square'] },
      { emoji: '5️⃣', name: 'five', keywords: ['5', 'numbers', 'blue_square', 'prime'] },
      { emoji: '6️⃣', name: 'six', keywords: ['6', 'numbers', 'blue_square'] },
      { emoji: '7️⃣', name: 'seven', keywords: ['7', 'numbers', 'blue_square', 'prime'] },
      { emoji: '8️⃣', name: 'eight', keywords: ['8', 'blue_square', 'numbers'] },
      { emoji: '9️⃣', name: 'nine', keywords: ['blue_square', 'numbers', '9'] },
      { emoji: '🔟', name: 'keycap_ten', keywords: ['numbers', '10', 'blue_square'] },
      { emoji: '🔢', name: '1234', keywords: ['numbers', 'blue_square'] },
      { emoji: '#️⃣', name: 'hash', keywords: ['symbol', 'blue_square', 'twitter'] },
      { emoji: '*️⃣', name: 'asterisk', keywords: ['star', 'keycap'] },
      { emoji: '⏏️', name: 'eject', keywords: ['blue_square'] },
      { emoji: '▶️', name: 'arrow_forward', keywords: ['blue_square', 'right', 'direction', 'play'] },
      { emoji: '⏸️', name: 'pause_button', keywords: ['pause', 'blue_square'] },
      { emoji: '⏯️', name: 'play_pause', keywords: ['blue_square', 'play', 'pause'] },
      { emoji: '⏹️', name: 'stop_button', keywords: ['blue_square'] },
      { emoji: '⏺️', name: 'record_button', keywords: ['blue_square'] },
      { emoji: '⏭️', name: 'track_next', keywords: ['forward', 'next', 'blue_square'] },
      { emoji: '⏮️', name: 'track_previous', keywords: ['backward', 'previous', 'blue_square'] },
      { emoji: '⏩', name: 'fast_forward', keywords: ['blue_square', 'play', 'speed', 'continue'] },
      { emoji: '⏪', name: 'rewind', keywords: ['play', 'blue_square'] },
      { emoji: '⏫', name: 'arrow_double_up', keywords: ['blue_square', 'direction', 'top'] },
      { emoji: '⏬', name: 'arrow_double_down', keywords: ['blue_square', 'direction', 'bottom'] },
      { emoji: '◀️', name: 'arrow_backward', keywords: ['blue_square', 'left', 'direction'] },
      { emoji: '🔼', name: 'arrow_up_small', keywords: ['blue_square', 'triangle', 'direction', 'point', 'forward', 'top'] },
      { emoji: '🔽', name: 'arrow_down_small', keywords: ['blue_square', 'direction', 'bottom'] },
      { emoji: '➡️', name: 'arrow_right', keywords: ['blue_square', 'next'] },
      { emoji: '⬅️', name: 'arrow_left', keywords: ['blue_square', 'previous', 'back'] },
      { emoji: '⬆️', name: 'arrow_up', keywords: ['blue_square', 'continue', 'top', 'direction'] },
      { emoji: '⬇️', name: 'arrow_down', keywords: ['blue_square', 'direction', 'bottom'] },
      { emoji: '↗️', name: 'arrow_upper_right', keywords: ['blue_square', 'point', 'direction', 'diagonal', 'northeast'] },
      { emoji: '↘️', name: 'arrow_lower_right', keywords: ['blue_square', 'direction', 'diagonal', 'southeast'] },
      { emoji: '↙️', name: 'arrow_lower_left', keywords: ['blue_square', 'direction', 'diagonal', 'southwest'] },
      { emoji: '↖️', name: 'arrow_upper_left', keywords: ['blue_square', 'point', 'direction', 'diagonal', 'northwest'] },
      { emoji: '↕️', name: 'arrow_up_down', keywords: ['blue_square', 'direction', 'way', 'vertical'] },
      { emoji: '↔️', name: 'left_right_arrow', keywords: ['shape', 'direction', 'horizontal', 'sideways'] },
      { emoji: '↪️', name: 'arrow_right_hook', keywords: ['blue_square', 'return', 'rotate', 'direction'] },
      { emoji: '↩️', name: 'leftwards_arrow_with_hook', keywords: ['return', 'blue_square', 'undo', 'enter'] },
      { emoji: '⤴️', name: 'arrow_heading_up', keywords: ['blue_square', 'direction', 'top'] },
      { emoji: '⤵️', name: 'arrow_heading_down', keywords: ['blue_square', 'direction', 'bottom'] },
      { emoji: '🔀', name: 'twisted_rightwards_arrows', keywords: ['blue_square', 'shuffle', 'music', 'random'] },
      { emoji: '🔁', name: 'repeat', keywords: ['loop', 'record'] },
      { emoji: '🔂', name: 'repeat_one', keywords: ['blue_square', 'loop'] },
      { emoji: '🔄', name: 'arrows_counterclockwise', keywords: ['blue_square', 'sync', 'cycle'] },
      { emoji: '🔃', name: 'arrows_clockwise', keywords: ['sync', 'cycle', 'round', 'repeat'] },
      { emoji: '🎵', name: 'musical_note', keywords: ['score', 'tone', 'sound'] },
      { emoji: '🎶', name: 'notes', keywords: ['music', 'score'] },
      { emoji: '➕', name: 'heavy_plus_sign', keywords: ['math', 'calculation', 'addition', 'more', 'increase'] },
      { emoji: '➖', name: 'heavy_minus_sign', keywords: ['math', 'calculation', 'subtract', 'less'] },
      { emoji: '➗', name: 'heavy_division_sign', keywords: ['divide', 'math', 'calculation'] },
      { emoji: '✖️', name: 'heavy_multiplication_x', keywords: ['math', 'calculation'] },
      { emoji: '♾️', name: 'infinity', keywords: ['forever'] },
      { emoji: '💲', name: 'heavy_dollar_sign', keywords: ['money', 'sales', 'payment', 'currency', 'buck'] },
      { emoji: '💱', name: 'currency_exchange', keywords: ['money', 'sales', 'dollar', 'travel'] },
      { emoji: '™️', name: 'tm', keywords: ['trademark', 'brand', 'law', 'legal'] },
      { emoji: '©️', name: 'copyright', keywords: ['ip', 'license', 'circle', 'law', 'legal'] },
      { emoji: '®️', name: 'registered', keywords: ['alphabet', 'circle'] },
      { emoji: '〰️', name: 'wavy_dash', keywords: ['draw', 'line', 'moustache', 'mustache', 'squiggle', 'scribble'] },
      { emoji: '➰', name: 'curly_loop', keywords: ['scribble', 'draw', 'shape', 'squiggle'] },
      { emoji: '➿', name: 'loop', keywords: ['tape', 'cassette'] },
      { emoji: '🔚', name: 'end', keywords: ['words', 'arrow'] },
      { emoji: '🔙', name: 'back', keywords: ['arrow', 'words'] },
      { emoji: '🔛', name: 'on', keywords: ['arrow', 'words'] },
      { emoji: '🔝', name: 'top', keywords: ['words', 'blue_square'] },
      { emoji: '🔜', name: 'soon', keywords: ['arrow', 'words'] },
      { emoji: '✔️', name: 'heavy_check_mark', keywords: ['ok', 'nike', 'answer', 'yes', 'tick'] },
      { emoji: '☑️', name: 'ballot_box_with_check', keywords: ['ok', 'agree', 'confirm', 'black_square', 'vote', 'yes', 'tick'] },
      { emoji: '🔘', name: 'radio_button', keywords: ['input', 'old', 'music', 'circle'] },
      { emoji: '🔴', name: 'red_circle', keywords: ['shape', 'error', 'danger'] },
      { emoji: '🟠', name: 'orange_circle', keywords: ['round'] },
      { emoji: '🟡', name: 'yellow_circle', keywords: ['round'] },
      { emoji: '🟢', name: 'green_circle', keywords: ['round'] },
      { emoji: '🔵', name: 'blue_circle', keywords: ['shape', 'icon', 'button'] },
      { emoji: '🟣', name: 'purple_circle', keywords: ['round'] },
      { emoji: '🟤', name: 'brown_circle', keywords: ['round'] },
      { emoji: '⚫', name: 'black_circle', keywords: ['shape', 'button', 'round'] },
      { emoji: '⚪', name: 'white_circle', keywords: ['shape', 'round'] },
      { emoji: '🟥', name: 'red_square', keywords: [] },
      { emoji: '🟧', name: 'orange_square', keywords: [] },
      { emoji: '🟨', name: 'yellow_square', keywords: [] },
      { emoji: '🟩', name: 'green_square', keywords: [] },
      { emoji: '🟦', name: 'blue_square', keywords: [] },
      { emoji: '🟪', name: 'purple_square', keywords: [] },
      { emoji: '🟫', name: 'brown_square', keywords: [] },
      { emoji: '⬛', name: 'black_large_square', keywords: ['shape', 'icon', 'button'] },
      { emoji: '⬜', name: 'white_large_square', keywords: ['shape', 'icon', 'stone', 'button'] },
      { emoji: '◼️', name: 'black_medium_square', keywords: ['shape', 'button', 'icon'] },
      { emoji: '◻️', name: 'white_medium_square', keywords: ['shape', 'stone', 'icon'] },
      { emoji: '◾', name: 'black_medium_small_square', keywords: ['icon', 'shape', 'button'] },
      { emoji: '◽', name: 'white_medium_small_square', keywords: ['shape', 'stone', 'icon', 'button'] },
      { emoji: '▪️', name: 'black_small_square', keywords: ['shape', 'icon'] },
      { emoji: '▫️', name: 'white_small_square', keywords: ['shape', 'icon'] },
      { emoji: '🔶', name: 'large_orange_diamond', keywords: ['shape', 'jewel', 'gem'] },
      { emoji: '🔷', name: 'large_blue_diamond', keywords: ['shape', 'jewel', 'gem'] },
      { emoji: '🔸', name: 'small_orange_diamond', keywords: ['shape', 'jewel', 'gem'] },
      { emoji: '🔹', name: 'small_blue_diamond', keywords: ['shape', 'jewel', 'gem'] },
      { emoji: '🔺', name: 'small_red_triangle', keywords: ['shape', 'direction', 'up', 'top'] },
      { emoji: '🔻', name: 'small_red_triangle_down', keywords: ['shape', 'direction', 'bottom'] },
      { emoji: '💠', name: 'diamond_shape_with_a_dot_inside', keywords: ['jewel', 'blue', 'gem', 'crystal', 'fancy'] },
      { emoji: '🔘', name: 'radio_button', keywords: ['input', 'old', 'music', 'circle'] },
      { emoji: '🔳', name: 'white_square_button', keywords: ['shape', 'input'] },
      { emoji: '🔲', name: 'black_square_button', keywords: ['shape', 'input', 'frame'] },
      { emoji: '🏁', name: 'checkered_flag', keywords: ['contest', 'finishline', 'race', 'gokart'] },
      { emoji: '🚩', name: 'triangular_flag', keywords: ['mark', 'milestone', 'place'] },
      { emoji: '🎌', name: 'crossed_flags', keywords: ['japanese', 'nation', 'country', 'border'] },
      { emoji: '🏴', name: 'flag_black', keywords: ['pirate'] },
      { emoji: '🏳️', name: 'flag_white', keywords: ['losing', 'loser', 'lost', 'surrender', 'give_up', 'fail'] },
      { emoji: '🏳️‍🌈', name: 'rainbow_flag', keywords: ['flag', 'pride', 'gay', 'lgbt', 'glbt', 'queer', 'homosexual', 'lesbian', 'bisexual', 'transgender'] },
      { emoji: '🏴‍☠️', name: 'pirate_flag', keywords: ['skull', 'crossbones', 'flag', 'banner'] },
    ],
  },
];


export const ALL_EMOJIS: EmojiItem[] = EMOJI_CATEGORIES.flatMap(cat => cat.emojis);


export const RECENTLY_USED_KEY = 'courtvision-recently-used-emojis';
export const MAX_RECENT_EMOJIS = 27; 
